[package]
name = "petgraph-evcxr"
version = "0.1.0"
authors = ["Timothy Hobbs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = ">= 0.10.1"
petgraph = ">= 0.4.13"
